
package org.librarypro.webapp.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpruntService", targetNamespace = "model.webapp.librarypro.org", wsdlLocation = "http://lfr023539:5050/librarypro-webservice-interface7091102566841682789//EmpruntService?wsdl")
public class EmpruntService
    extends Service
{

    private final static URL EMPRUNTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPRUNTSERVICE_EXCEPTION;
    private final static QName EMPRUNTSERVICE_QNAME = new QName("model.webapp.librarypro.org", "EmpruntService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr023539:5050/librarypro-webservice-interface7091102566841682789//EmpruntService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRUNTSERVICE_WSDL_LOCATION = url;
        EMPRUNTSERVICE_EXCEPTION = e;
    }

    public EmpruntService() {
        super(__getWsdlLocation(), EMPRUNTSERVICE_QNAME);
    }

    public EmpruntService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPRUNTSERVICE_QNAME, features);
    }

    public EmpruntService(URL wsdlLocation) {
        super(wsdlLocation, EMPRUNTSERVICE_QNAME);
    }

    public EmpruntService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPRUNTSERVICE_QNAME, features);
    }

    public EmpruntService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpruntService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpruntClient
     */
    @WebEndpoint(name = "EmpruntPort")
    public EmpruntClient getEmpruntPort() {
        return super.getPort(new QName("model.webapp.librarypro.org", "EmpruntPort"), EmpruntClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpruntClient
     */
    @WebEndpoint(name = "EmpruntPort")
    public EmpruntClient getEmpruntPort(WebServiceFeature... features) {
        return super.getPort(new QName("model.webapp.librarypro.org", "EmpruntPort"), EmpruntClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRUNTSERVICE_EXCEPTION!= null) {
            throw EMPRUNTSERVICE_EXCEPTION;
        }
        return EMPRUNTSERVICE_WSDL_LOCATION;
    }

}
