
package org.librarypro.webapp.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OuvrageService", targetNamespace = "model.webapp.librarypro.org", wsdlLocation = "http://lfr023539:5050/librarypro-webservice-interface7091102566841682789//OuvrageService?wsdl")
public class OuvrageService
    extends Service
{

    private final static URL OUVRAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException OUVRAGESERVICE_EXCEPTION;
    private final static QName OUVRAGESERVICE_QNAME = new QName("model.webapp.librarypro.org", "OuvrageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lfr023539:5050/librarypro-webservice-interface7091102566841682789//OuvrageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OUVRAGESERVICE_WSDL_LOCATION = url;
        OUVRAGESERVICE_EXCEPTION = e;
    }

    public OuvrageService() {
        super(__getWsdlLocation(), OUVRAGESERVICE_QNAME);
    }

    public OuvrageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OUVRAGESERVICE_QNAME, features);
    }

    public OuvrageService(URL wsdlLocation) {
        super(wsdlLocation, OUVRAGESERVICE_QNAME);
    }

    public OuvrageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OUVRAGESERVICE_QNAME, features);
    }

    public OuvrageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OuvrageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OuvrageClient
     */
    @WebEndpoint(name = "OuvragePort")
    public OuvrageClient getOuvragePort() {
        return super.getPort(new QName("model.webapp.librarypro.org", "OuvragePort"), OuvrageClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OuvrageClient
     */
    @WebEndpoint(name = "OuvragePort")
    public OuvrageClient getOuvragePort(WebServiceFeature... features) {
        return super.getPort(new QName("model.webapp.librarypro.org", "OuvragePort"), OuvrageClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OUVRAGESERVICE_EXCEPTION!= null) {
            throw OUVRAGESERVICE_EXCEPTION;
        }
        return OUVRAGESERVICE_WSDL_LOCATION;
    }

}
