
package org.librarypro.webapp.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpruntClient", targetNamespace = "model.webapp.librarypro.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpruntClient {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.AddResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/addRequest", output = "model.webapp.librarypro.org/EmpruntClient/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        EmpruntDTO arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.EmpruntDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.ListResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/listRequest", output = "model.webapp.librarypro.org/EmpruntClient/listResponse")
    public List<EmpruntDTO> list();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "print", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.PrintResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/printRequest", output = "model.webapp.librarypro.org/EmpruntClient/printResponse")
    public void print();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.EmpruntDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "empruntsByUtilisateur", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.EmpruntsByUtilisateur")
    @ResponseWrapper(localName = "empruntsByUtilisateurResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.EmpruntsByUtilisateurResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/empruntsByUtilisateurRequest", output = "model.webapp.librarypro.org/EmpruntClient/empruntsByUtilisateurResponse")
    public List<EmpruntDTO> empruntsByUtilisateur(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prolonge", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Prolonge")
    @ResponseWrapper(localName = "prolongeResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.ProlongeResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/prolongeRequest", output = "model.webapp.librarypro.org/EmpruntClient/prolongeResponse")
    public String prolonge(
        @WebParam(name = "arg0", targetNamespace = "")
        EmpruntDTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "prolonger", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Prolonger")
    @ResponseWrapper(localName = "prolongerResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.ProlongerResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/prolongerRequest", output = "model.webapp.librarypro.org/EmpruntClient/prolongerResponse")
    public void prolonger(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.EmpruntDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "empruntsEnCours", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.EmpruntsEnCours")
    @ResponseWrapper(localName = "empruntsEnCoursResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.EmpruntsEnCoursResponse")
    @Action(input = "model.webapp.librarypro.org/EmpruntClient/empruntsEnCoursRequest", output = "model.webapp.librarypro.org/EmpruntClient/empruntsEnCoursResponse")
    public List<EmpruntDTO> empruntsEnCours();

}
