
package org.librarypro.webapp.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationClient", targetNamespace = "model.webapp.librarypro.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationClient {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.AddResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/addRequest", output = "model.webapp.librarypro.org/ReservationClient/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservationDTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.UpdateResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/updateRequest", output = "model.webapp.librarypro.org/ReservationClient/updateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservationDTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.DeleteResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/deleteRequest", output = "model.webapp.librarypro.org/ReservationClient/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservationDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.ReservationDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListByOuvrage", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetListByOuvrage")
    @ResponseWrapper(localName = "getListByOuvrageResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetListByOuvrageResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/getListByOuvrageRequest", output = "model.webapp.librarypro.org/ReservationClient/getListByOuvrageResponse")
    public List<ReservationDTO> getListByOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.ReservationDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetListResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/getListRequest", output = "model.webapp.librarypro.org/ReservationClient/getListResponse")
    public List<ReservationDTO> getList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.librarypro.webapp.model.ReservationDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListByOuvrageTriee", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetListByOuvrageTriee")
    @ResponseWrapper(localName = "getListByOuvrageTrieeResponse", targetNamespace = "model.webapp.librarypro.org", className = "org.librarypro.webapp.model.GetListByOuvrageTrieeResponse")
    @Action(input = "model.webapp.librarypro.org/ReservationClient/getListByOuvrageTrieeRequest", output = "model.webapp.librarypro.org/ReservationClient/getListByOuvrageTrieeResponse")
    public List<ReservationDTO> getListByOuvrageTriee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
